remote_theme: pages-themes/minimal@v0.2.0
# logo: https://github.com/MarkMData/portfolio/blob/main/images/profile_photo.jpg
plugins:
- jekyll-remote-theme
title: Mark Morrison Project Portfolio
markdown: GFM
